--------------------------------------------------------
--  Arquivo criado - Segunda-feira-Novembro-11-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence AMIZADE_ID_AMIZADE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "REDESOCIAL"."AMIZADE_ID_AMIZADE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence COMENTARIO_ID_COMENTARIO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "REDESOCIAL"."COMENTARIO_ID_COMENTARIO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence CURTIDA_ID_CURTIDA_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "REDESOCIAL"."CURTIDA_ID_CURTIDA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence POSTAGEM_ID_POSTAGEM_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "REDESOCIAL"."POSTAGEM_ID_POSTAGEM_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence USUARIO_ID_USUARIO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "REDESOCIAL"."USUARIO_ID_USUARIO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table AMIZADE
--------------------------------------------------------

  CREATE TABLE "REDESOCIAL"."AMIZADE" 
   (	"ID" NUMBER, 
	"ID_SOLICITANTE" NUMBER, 
	"ID_SOLICITADO" NUMBER, 
	"ACEITADO" NUMBER(1,0), 
	"DATA_AMIZADE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table COMENTARIO
--------------------------------------------------------

  CREATE TABLE "REDESOCIAL"."COMENTARIO" 
   (	"ID" NUMBER, 
	"ID_USUARIO" NUMBER, 
	"ID_POST" NUMBER, 
	"TEXTO" VARCHAR2(255 BYTE), 
	"DATA" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CURTIDA
--------------------------------------------------------

  CREATE TABLE "REDESOCIAL"."CURTIDA" 
   (	"ID" NUMBER, 
	"ID_USUARIO_CURTIDOR" NUMBER, 
	"ID_POSTAGEM" NUMBER, 
	"DATA" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table POSTAGEM
--------------------------------------------------------

  CREATE TABLE "REDESOCIAL"."POSTAGEM" 
   (	"ID" NUMBER, 
	"ID_USUARIO" NUMBER, 
	"DATA" DATE, 
	"NUMERO_CURTIDAS" NUMBER(10,0), 
	"TEXTO" VARCHAR2(255 BYTE), 
	"FOTO" VARCHAR2(512 BYTE), 
	"PRIVADO" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USUARIO
--------------------------------------------------------

  CREATE TABLE "REDESOCIAL"."USUARIO" 
   (	"ID" NUMBER, 
	"NOME_COMPLETO" VARCHAR2(255 BYTE), 
	"EMAIL" VARCHAR2(255 BYTE), 
	"APELIDO" VARCHAR2(50 BYTE), 
	"DATA_NASCIMENTO" DATE, 
	"SENHA" VARCHAR2(128 BYTE), 
	"IMAGEM_PERFIL" VARCHAR2(512 BYTE), 
	"PAIS_ORIGEM" VARCHAR2(255 BYTE), 
	"PAIS_ATUAL" VARCHAR2(255 BYTE), 
	"ATIVO" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index AMIZADE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "REDESOCIAL"."AMIZADE_PK" ON "REDESOCIAL"."AMIZADE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index COMENTARIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "REDESOCIAL"."COMENTARIO_PK" ON "REDESOCIAL"."COMENTARIO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CURTIDA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "REDESOCIAL"."CURTIDA_PK" ON "REDESOCIAL"."CURTIDA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index POSTAGEM_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "REDESOCIAL"."POSTAGEM_PK" ON "REDESOCIAL"."POSTAGEM" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index USUARIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "REDESOCIAL"."USUARIO_PK" ON "REDESOCIAL"."USUARIO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table POSTAGEM
--------------------------------------------------------

  ALTER TABLE "REDESOCIAL"."POSTAGEM" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "REDESOCIAL"."POSTAGEM" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "REDESOCIAL"."POSTAGEM" MODIFY ("DATA" NOT NULL ENABLE);
  ALTER TABLE "REDESOCIAL"."POSTAGEM" MODIFY ("NUMERO_CURTIDAS" NOT NULL ENABLE);
  ALTER TABLE "REDESOCIAL"."POSTAGEM" MODIFY ("TEXTO" NOT NULL ENABLE);
  ALTER TABLE "REDESOCIAL"."POSTAGEM" MODIFY ("PRIVADO" NOT NULL ENABLE);
  ALTER TABLE "REDESOCIAL"."POSTAGEM" ADD CONSTRAINT "POSTAGEM_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CURTIDA
--------------------------------------------------------

  ALTER TABLE "REDESOCIAL"."CURTIDA" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "REDESOCIAL"."CURTIDA" MODIFY ("ID_USUARIO_CURTIDOR" NOT NULL ENABLE);
  ALTER TABLE "REDESOCIAL"."CURTIDA" MODIFY ("ID_POSTAGEM" NOT NULL ENABLE);
  ALTER TABLE "REDESOCIAL"."CURTIDA" MODIFY ("DATA" NOT NULL ENABLE);
  ALTER TABLE "REDESOCIAL"."CURTIDA" ADD CONSTRAINT "CURTIDA_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table AMIZADE
--------------------------------------------------------

  ALTER TABLE "REDESOCIAL"."AMIZADE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "REDESOCIAL"."AMIZADE" MODIFY ("ID_SOLICITANTE" NOT NULL ENABLE);
  ALTER TABLE "REDESOCIAL"."AMIZADE" MODIFY ("ID_SOLICITADO" NOT NULL ENABLE);
  ALTER TABLE "REDESOCIAL"."AMIZADE" MODIFY ("ACEITADO" NOT NULL ENABLE);
  ALTER TABLE "REDESOCIAL"."AMIZADE" ADD CONSTRAINT "AMIZADE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "REDESOCIAL"."AMIZADE" MODIFY ("DATA_AMIZADE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USUARIO
--------------------------------------------------------

  ALTER TABLE "REDESOCIAL"."USUARIO" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "REDESOCIAL"."USUARIO" MODIFY ("NOME_COMPLETO" NOT NULL ENABLE);
  ALTER TABLE "REDESOCIAL"."USUARIO" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "REDESOCIAL"."USUARIO" MODIFY ("DATA_NASCIMENTO" NOT NULL ENABLE);
  ALTER TABLE "REDESOCIAL"."USUARIO" MODIFY ("SENHA" NOT NULL ENABLE);
  ALTER TABLE "REDESOCIAL"."USUARIO" MODIFY ("PAIS_ORIGEM" NOT NULL ENABLE);
  ALTER TABLE "REDESOCIAL"."USUARIO" MODIFY ("PAIS_ATUAL" NOT NULL ENABLE);
  ALTER TABLE "REDESOCIAL"."USUARIO" MODIFY ("ATIVO" NOT NULL ENABLE);
  ALTER TABLE "REDESOCIAL"."USUARIO" ADD CONSTRAINT "USUARIO_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "REDESOCIAL"."USUARIO" ADD UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table COMENTARIO
--------------------------------------------------------

  ALTER TABLE "REDESOCIAL"."COMENTARIO" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "REDESOCIAL"."COMENTARIO" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "REDESOCIAL"."COMENTARIO" MODIFY ("ID_POST" NOT NULL ENABLE);
  ALTER TABLE "REDESOCIAL"."COMENTARIO" MODIFY ("TEXTO" NOT NULL ENABLE);
  ALTER TABLE "REDESOCIAL"."COMENTARIO" MODIFY ("DATA" NOT NULL ENABLE);
  ALTER TABLE "REDESOCIAL"."COMENTARIO" ADD CONSTRAINT "COMENTARIO_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table AMIZADE
--------------------------------------------------------

  ALTER TABLE "REDESOCIAL"."AMIZADE" ADD CONSTRAINT "AMIZADE_fk0" FOREIGN KEY ("ID_SOLICITANTE")
	  REFERENCES "REDESOCIAL"."USUARIO" ("ID") ENABLE;
  ALTER TABLE "REDESOCIAL"."AMIZADE" ADD CONSTRAINT "AMIZADE_fk1" FOREIGN KEY ("ID_SOLICITADO")
	  REFERENCES "REDESOCIAL"."USUARIO" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COMENTARIO
--------------------------------------------------------

  ALTER TABLE "REDESOCIAL"."COMENTARIO" ADD CONSTRAINT "COMENTARIO_fk0" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "REDESOCIAL"."USUARIO" ("ID") ENABLE;
  ALTER TABLE "REDESOCIAL"."COMENTARIO" ADD CONSTRAINT "COMENTARIO_fk1" FOREIGN KEY ("ID_POST")
	  REFERENCES "REDESOCIAL"."POSTAGEM" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CURTIDA
--------------------------------------------------------

  ALTER TABLE "REDESOCIAL"."CURTIDA" ADD CONSTRAINT "CURTIDA_fk0" FOREIGN KEY ("ID_USUARIO_CURTIDOR")
	  REFERENCES "REDESOCIAL"."USUARIO" ("ID") ENABLE;
  ALTER TABLE "REDESOCIAL"."CURTIDA" ADD CONSTRAINT "CURTIDA_fk1" FOREIGN KEY ("ID_POSTAGEM")
	  REFERENCES "REDESOCIAL"."POSTAGEM" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table POSTAGEM
--------------------------------------------------------

  ALTER TABLE "REDESOCIAL"."POSTAGEM" ADD CONSTRAINT "POSTAGEM_fk0" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "REDESOCIAL"."USUARIO" ("ID") ENABLE;
