
CREATE TABLE "USUARIO" (
	"ID" NUMBER NOT NULL,
	"NOME_COMPLETO" VARCHAR2(255) NOT NULL,
	"EMAIL" VARCHAR2(255) UNIQUE NOT NULL,
	"APELIDO" VARCHAR2(50),
	"DATA_NASCIMENTO" DATE NOT NULL,
	"SENHA" VARCHAR2(128) NOT NULL,
	"IMAGEM_PERFIL" VARCHAR2(512),
	"PAIS_ORIGEM" VARCHAR2(255) NOT NULL,
	"PAIS_ATUAL" VARCHAR2(255) NOT NULL,
	"ATIVO" NUMBER(1) NOT NULL,
	constraint USUARIO_PK PRIMARY KEY ("ID"));


/
CREATE TABLE "POSTAGEM" (
	"ID" NUMBER NOT NULL,
	"ID_USUARIO" NUMBER NOT NULL,
	"DATA" DATE NOT NULL,
	"NUMERO_CURTIDAS" NUMBER(10) NOT NULL,
	"TEXTO" VARCHAR2(255) NOT NULL,
	"FOTO" VARCHAR2(512),
	"PRIVADO" NUMBER(1) NOT NULL,
	constraint POSTAGEM_PK PRIMARY KEY ("ID"));


/
CREATE TABLE "CURTIDA" (
	"ID" NUMBER NOT NULL,
	"ID_USUARIO_CURTIDOR" NUMBER NOT NULL,
	"ID_POSTAGEM" NUMBER NOT NULL,
	"DATA" DATE NOT NULL,
	constraint CURTIDA_PK PRIMARY KEY ("ID"));
/


CREATE TABLE "COMENTARIO" (
	"ID" NUMBER NOT NULL,
	"ID_USUARIO" NUMBER NOT NULL,
	"ID_POST" NUMBER NOT NULL,
	"TEXTO" VARCHAR2(255) NOT NULL,
	"DATA" DATE NOT NULL,
	constraint COMENTARIO_PK PRIMARY KEY ("ID"));
/

CREATE TABLE "AMIZADE" (
	"ID" NUMBER NOT NULL,
	"ID_SOLICITANTE" NUMBER NOT NULL,
	"ID_SOLICITADO" NUMBER NOT NULL,
	"ACEITADO" NUMBER(1) NOT NULL,
	"DATA_AMIZADE" DATE NOT NULL,
	constraint AMIZADE_PK PRIMARY KEY ("ID"));
/


ALTER TABLE "POSTAGEM" ADD CONSTRAINT "POSTAGEM_fk0" FOREIGN KEY ("ID_USUARIO") REFERENCES "USUARIO"("ID");
ALTER TABLE "AMIZADE" ADD CONSTRAINT "AMIZADE_fk0" FOREIGN KEY ("ID_SOLICITANTE") REFERENCES "USUARIO"("ID");
ALTER TABLE "AMIZADE" ADD CONSTRAINT "AMIZADE_fk1" FOREIGN KEY ("ID_SOLICITADO") REFERENCES "USUARIO"("ID");
ALTER TABLE "CURTIDA" ADD CONSTRAINT "CURTIDA_fk0" FOREIGN KEY ("ID_USUARIO_CURTIDOR") REFERENCES "USUARIO"("ID");
ALTER TABLE "CURTIDA" ADD CONSTRAINT "CURTIDA_fk1" FOREIGN KEY ("ID_POST") REFERENCES "POSTAGEM"("ID");
ALTER TABLE "COMENTARIO" ADD CONSTRAINT "COMENTARIO_fk0" FOREIGN KEY ("ID_USUARIO") REFERENCES "USUARIO"("ID");
ALTER TABLE "COMENTARIO" ADD CONSTRAINT "COMENTARIO_fk1" FOREIGN KEY ("ID_POST") REFERENCES "POSTAGEM"("ID");


CREATE sequence POSTAGEM_ID_POSTAGEM_SEQ;

CREATE sequence AMIZADE_ID_AMIZADE_SEQ;

CREATE sequence USUARIO_ID_USUARIO_SEQ;

CREATE sequence CURTIDA_ID_CURTIDA_SEQ;

CREATE sequence COMENTARIO_ID_COMENTARIO_SEQ;